# php -> mysql -> redis -> nginx

version: "3.8"

services:
  aplicacao:
    build:
      context: .
    volumes:
      - sessao:/tmp

  banco_dados:
    image: mysql:8.0
    volumes:
      - "dbdata:/var/lib/mysql"        
    environment:
      MYSQL_ROOT_PASSWORD: example

  gerenciador_sessao:
    image: redis:7.0


volumes:
  sessao:
  dbdata:

